# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
  dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Dist
      run: |
        rm -rf dist
        GOOS='darwin' GOARCH='amd64' go build -x -v -a -o 'dist/darwin/amd64/kurse' .
        GOOS='linux'  GOARCH='amd64' go build -x -v -a -o 'dist/linux/amd64/kurse'  .
        GOOS='linux'  GOARCH='arm'   go build -x -v -a -o 'dist/linux/arm/kurse'    .
        GOOS='linux'  GOARCH='arm64' go build -x -v -a -o 'dist/linux/arm64/kurse'  .
        ls -hl dist/*      
